### ISSUE TITLE
Render error on /gene/ENSG00000122970

### ISSUE THREAD

**Issue by emmamiles** [macarthur-lab/gnomadjs#411]
### What you did:
Trying to load IFT81 gene in gnomAD. https://gnomad.broadinstitute.org/gene/ENSG00000122970.

### What happened:

it didn't load, see message below. 
Something Went Wrong
An error occurred while rendering this page.

This is a bug. Please file an issue on GitHub and reload the browser.

**Comment by nawatts** [comment]
Hi @emmamiles,

It looks like the IFT81  gene page is rendering now, so this seems like it was an intermittent problem maybe caused by an issue with a database connection.

In any case, the page should still render with a more descriptive error message, so I'll keep this issue open for investigation.
