### ISSUE TITLE
AN is less than 10K in gnomAD v3 VCF files

### ISSUE THREAD

**Issue by jiehuang001** [macarthur-lab/gnomadjs#524]
Hi, 

I am downloading the gnomAD summary VCF v3 files from https://storage.googleapis.com/gnomad-public/release/3.0/vcf/genomes/gnomad.genomes.r3.0.sites.vcf.bgz

I checked the AN fields for the first few SNPs, and found that the AN is around 2,000 to 4,000. How could this be the case? 
The gnomAD FAQ page says that “The gnomAD v3 data set contains 71,702 whole genomes (and no exomes)”. 
So, AN should be around 142K…., right?

Can you please kindly clarify?

Thank you & Best regards,
Jie

**Comment by nawatts** [comment]
Hi @jiehuang001,

Only high quality genotypes are counted towards allele number. Thus, AN varies along the genome because not all regions are equally covered in all samples.

For example, in the region [1-1-100000](https://gnomad.broadinstitute.org/region/1-1-100000?dataset=gnomad_r3), AN varies between 18 and 143,400.
