### ISSUE TITLE
API: gencode version instead of reference genome

### ISSUE THREAD

**Issue by mhebrard** [macarthur-lab/gnomadjs#535]
I noticed that the API endpoint of `gene`, `transcript` and `region` require `reference_genome` as argument. The only usage of this argument is to define the gencode version and it is tested at multiple place in the API.

Would it be smarter to pass directly the gencode version as argument ?

That would require to change the signature of the API but that will avoid to hard code the reference genome and the gencode version at multiple places. It will also make it easier to upgrade to a new version of gencode.

Let me know your thoughts

**Comment by nawatts** [comment]
Hi @mhebrard,

Using Gencode version instead of reference genome would be more precise and possibly slightly clearer.

However, for the gnomAD browser, the distinction between reference genomes is more important than between Gencode versions. Not all data shown on the same page will necessarily be based on the same version of Gencode.

For example, the GTEx data used to display tissue expression in the transcripts track. For GRCh38, the only GTEx data available is based on Gencode 26, not 29. If the argument for gene/region/transcript was Gencode version instead of reference genome, then the gnomAD v3 pages would need to separately request tissue expression from the API since it is based on a different version of Gencode than most other data on the page. And no other data besides tissue expression would be available for Gencode 26. Using the more general reference genome as the argument allows us to group that data together and simplify the request logic.

Also, we don’t have plans to keep multiple versions of gnomAD within the same reference genome available in the browser. So most likely, for API purposes, there will only ever be one version of Gencode associated with a reference genome.
