### ISSUE TITLE
issues caused by the redirect from http to https when retrieving data from graphql api

### ISSUE THREAD

**Issue by monkollek** [macarthur-lab/gnomadjs#536]
The recent redirect from http to https causes issues with existing code that's using graphql-request to retrieve data if it was previously using http://gnomad.broadinstitute.org/api 

curl http://gnomad.broadinstitute.org/api
Found. Redirecting to https://gnomad.broadinstitute.org/api

I'm guessing that graphql-request doesn't handle redirects. Other code may also have this issue.

**Comment by nawatts** [comment]
Hi @monkollek,

Yes, the effect of the redirect on API queries was overlooked. I believe the problem is that the browser returns a 302 status for HTTP requests. Most clients change the request method to GET when following 302 redirects, which interferes with POST requests to the API endpoint. Instead, it should respond with a 307 or 308, which require keeping the same request method.
